Added Test Report Github Action

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,10 +18,12 @@ jobs:
         run: sbt compile
       - name: Test
         run: sbt test
-          - uses: dorny/test-reporter@v1
-               with:
-                 artifact: test-results            # artifact name
-                 name: Scala Tests                  # Name of the check run which will be created
-                 path: '**/test-reports/*.xml'                     # Path to test results (inside artifact .zip)
-                 reporter: java-junit
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Scala Tests            # Name of the check run which will be created
+          path: "**/test-reports/*.xml"    # Path to test results
+          reporter: java-junit        # Format of test results
+
 
